# Generated by Django 5.2.6 on 2025-09-07 01:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('admission_date', models.DateField(default=datetime.date.today)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='child_photos/')),
                ('need', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_allocated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NeedDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='General Need', max_length=150)),
                ('section', models.CharField(choices=[('Food', 'Food'), ('Education', 'Education'), ('Clothing', 'Clothing'), ('Health', 'Health'), ('Other', 'Other')], default='Other', max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fulfilled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Orphanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_allocations', to='orphanage.child')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_allocations', to='orphanage.donation')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='orphanage.donor'),
        ),
        migrations.CreateModel(
            name='DonationAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='orphanage.donation')),
                ('need_donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='orphanage.needdonation')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='allocated_need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='orphanage.needdonation'),
        ),
        migrations.AddField(
            model_name='needdonation',
            name='orphanage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='orphanage.orphanage'),
        ),
        migrations.CreateModel(
            name='StaffAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_allocations', to='orphanage.child')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_allocations', to='orphanage.staff')),
            ],
        ),
    ]
