# Generated by Django 5.2.6 on 2025-09-07 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationallocation',
            name='amount_allocated',
        ),
        migrations.RemoveField(
            model_name='donationallocation',
            name='need_donation',
        ),
        migrations.AddField(
            model_name='donationallocation',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orphanage.child'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='allocated_need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orphanage.needdonation'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.donor'),
        ),
        migrations.AlterField(
            model_name='donationallocation',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_allocations_allocation', to='orphanage.donation'),
        ),
    ]
