# Generated by Django 5.2.6 on 2025-09-07 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0002_remove_donationallocation_amount_allocated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orphanage_name', models.CharField(max_length=100)),
                ('total_amount', models.FloatField()),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='allocation',
            old_name='allocated_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='donationallocation',
            old_name='allocated_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='donationallocation',
            name='child',
        ),
        migrations.AddField(
            model_name='allocation',
            name='allocated_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='donationallocation',
            name='allocated_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='donationallocation',
            name='need',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orphanage.needdonation'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.child'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='allocated_need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='orphanage.needdonation'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='orphanage.donor'),
        ),
        migrations.AlterField(
            model_name='donationallocation',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_allocations', to='orphanage.donation'),
        ),
        migrations.CreateModel(
            name='ExpenseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_allocations', to='orphanage.child')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='orphanage.expense')),
            ],
        ),
    ]
