# Generated by Django 5.2.6 on 2025-09-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0003_expense_rename_allocated_at_allocation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='orphanage.child'),
        ),
        migrations.AlterField(
            model_name='donationallocation',
            name='need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='orphanage.needdonation'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='orphanage_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='needdonation',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
