# Generated by Django 5.2.6 on 2025-09-07 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0004_alter_allocation_child_alter_donationallocation_need_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationallocation',
            old_name='date',
            new_name='allocated_at',
        ),
        migrations.RenameField(
            model_name='donationallocation',
            old_name='need',
            new_name='need_donation',
        ),
        migrations.RemoveField(
            model_name='donationallocation',
            name='allocated_amount',
        ),
        migrations.AddField(
            model_name='child',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='donationallocation',
            name='amount_allocated',
            field=models.DecimalField(decimal_places=2, max_digits=10, default=0),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='allocated_amount',
            field=models.FloatField(db_column='amount'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.child'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_column='allocated_at'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.donation'),
        ),
        migrations.AlterField(
            model_name='donationallocation',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='orphanage.donation'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='orphanage_name',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='needdonation',
            name='category',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
    ]
