# Generated by Django 5.2.6 on 2025-09-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0005_rename_date_donationallocation_allocated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='child_need_fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donationallocation',
            name='amount_allocated',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='needdonation',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
