# Generated by Django 5.2.6 on 2025-09-08 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0006_child_child_need_fulfilled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationallocation',
            old_name='amount_allocated',
            new_name='allocated_amount',
        ),
        migrations.RenameField(
            model_name='donationallocation',
            old_name='allocated_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='donationallocation',
            name='need_donation',
        ),
        migrations.AddField(
            model_name='donationallocation',
            name='allocated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationallocation',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orphanage.child'),
        ),
        migrations.AddField(
            model_name='donationallocation',
            name='need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orphanage.needdonation'),
        ),
        migrations.AlterField(
            model_name='donationallocation',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.donation'),
        ),
    ]
