# Generated by Django 5.0.3 on 2025-09-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0008_adopter_adoptionapplication_adoptioninterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='adoption_notes',
            field=models.TextField(blank=True, help_text='Special notes for potential adopters', null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='background',
            field=models.TextField(blank=True, help_text="Child's background story and history", null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Child's date of birth", null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='dietary_requirements',
            field=models.TextField(blank=True, help_text='Any dietary restrictions or preferences', null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='education_level',
            field=models.CharField(blank=True, help_text='Current education level', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='favorite_subjects',
            field=models.CharField(blank=True, help_text='Favorite subjects or activities', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='health_status',
            field=models.TextField(blank=True, help_text='Health conditions and medical information', null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='hobbies_interests',
            field=models.TextField(blank=True, help_text="Child's hobbies, interests, and activities", null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='is_available_for_adoption',
            field=models.BooleanField(default=True, help_text='Whether child is available for adoption'),
        ),
        migrations.AddField(
            model_name='child',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='Languages the child speaks', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='personality',
            field=models.TextField(blank=True, help_text="Child's personality traits and characteristics", null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='special_skills',
            field=models.TextField(blank=True, help_text='Special talents or skills', null=True),
        ),
    ]
